version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg-data:

